#ifndef COLLISION_OBJECT_TYPE_H
#define COLLISION_OBJECT_TYPE_H

enum class collision_object_type
{
	STRUCTURE,
	STRUCTURE_PAINTABLE,
	STRUCTURE_JUMP_THROUGH,
	PLAYER_TEAM_A,
	PLAYER_TEAM_B,
	PLAYER_TEAM_A_DEAD,
	PLAYER_TEAM_B_DEAD,
	PROJECTILE_SPRAY_TEAM_A,
	PROJECTILE_SPRAY_TEAM_B,
	PROJECTILE_JET_TEAM_A,
	PROJECTILE_JET_TEAM_B,
	PROJECTILE_ROLLING_TEAM_A,
	PROJECTILE_ROLLING_TEAM_B,
	PROJECTILE_BALL_TEAM_A,
	PROJECTILE_BALL_TEAM_B,
	PROJECTILE_MIST_TEAM_A,
	PROJECTILE_MIST_TEAM_B,
	PAINT_TILE,
	POWER_UP,
	DEFAULT,
	NONE
};

#endif // !COLLISION_OBJECT_TYPE_H
